#Feature: Data Upload Utility (DUU) - Linked Facility details
#
#	Scenario Outline: Get API to fetch linked facility details for ic-admin, ic-user, surgeon, nurse, hospital-admin users
#	
#		Given required base url, authorization "<key>" "<value>" are available
#		When get api is triggered to fetch linked facility details
#		Then verify status code 200 is returned for Get API to fetch linked facility details
#		And verify response body provides required linked facility details for logged in user
#		
#		Examples:
#		| key           | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       																										|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 																										|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1NGExZjhlZC02YjMyLTRkNTYtOGNmOC1iMmNhYmNlZTA0MGQiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzY2NDY5ZDU5LTc1NDMtNDk1NS05ODdlLTQ0ZmM4N2RmNjJhNSIsImNvZ25pdG86Z3JvdXBzIjpbImljLXVzZXIiXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfUGh3aTVtd1llIiwiY2xpZW50X2lkIjoiN2p0cG9ucHE0b3Y4dDF1MXA5cXV1N2U2czkiLCJvcmlnaW5fanRpIjoiZWUwNWMzMTYtYjFjMC00NzU2LWE4YjQtYmQyZmE5YjI4ODA3IiwiZXZlbnRfaWQiOiJiNTBmZjAxNy1hYWFmLTQwZmQtODEyNi0zNDFlYzY0MTI4OWIiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjU3MTc2NjYwLCJleHAiOjE2NTcxODAyNjQsImlhdCI6MTY1NzE3NjY2NCwianRpIjoiZDVjYTRiZWMtYTdiYi00YzNkLWEwYzUtMGVhZTlkMTg0NzViIiwidXNlcm5hbWUiOiJpYy10ZXN0LXRlY2hAY2FwZ2VtaW5pLmNvbSJ9.KS3NuFOIabgtcqmbkw9_2fKQG9FwpjnHxWf5073fLvWutlkCsmcpXpy_d8Iwxzfppqytqa6gp6DVLNY1LYHvrDFfeXAjnMoXhyGftPPs9bBdy4n52fzMJTZgVSKrqGML9VgVvxf9lBTrnECdowHE5VztZI-pSfOM7qfIqsYyNF00YFwe2pazFm766__lSNirikdIOe8wtEXp7IgUsPoevpsIOKvZE-R3b_PNit_Ryctc7k87EAAAYzsx-yb5M7YsY18zrfiSOLppJSXkP-QwG8qrqjO4y635GiKXj3lTirBVM5TvI-sB3rkBvLoZUwc3y0IuXWy5JaMJZhwZq9__QA				|
#   		| Authorization | Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2ODZiNjdhYS1iZTllLTQ3YjUtYjYxZi1jNzM4ZTcwNWM1MDUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzFhZTI2MjViLTZjNWMtNGYxMC1hMTIyLWIzYmQyZGU2ZjUzZiIsImNvZ25pdG86Z3JvdXBzIjpbInN1cmdlb24iXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfY1dNTmpDU1ZiIiwiY2xpZW50X2lkIjoiN245aGI0YnJyNHVuMmwwbTByNDBwOGY2OWoiLCJldmVudF9pZCI6ImJjMmRhZGY3LTc4YjktNDk2Ni05MzFmLWRlOTQ5YjIzZWI2NiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NDU1OTE3ODEsImV4cCI6MTY0NTU5NTQ1MiwiaWF0IjoxNjQ1NTkxODUyLCJqdGkiOiJjYzU4OWFlZC02YjI1LTQ5MGEtOTUzZC0zMTRjMDFjYjkxZGEiLCJ1c2VybmFtZSI6IlN1cmdlb25BQiJ9.RvhHXDsiv_3ldgC2gPqow0AuLIjfJrOL2-uxSZp7Yt5TDYFQ6-hp1BO99XHDsBCvzIK-dLUTJPhJoGokA68ySdvKanvukZQCwQo0yVUhUozbbMv2kvhMH29-85ekxymweRZOghEoGlAwYYFCoFSTsFWa_9Xd3gSYvfTzeAgDxVRn-rI-gt5LR-4FurMjCw6LdBNZJp4lQIY4PTQ8cJsfEqaDSGmgODr0-TniHJ5dpT2jZiTvv6HQKBoHAV5i8PAA6mjBg0HPrS2uuGXjTvqPIg9DLRf_eMNe1bFSQLvioOJuL2BZ0x6Wf1H8__0dfGaaSS1P5uUvTMDdc1DQNoVopQ 																											|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI5OWZlZDM5Ny1lMDc5LTQzZTEtYjE0OS05MDZiZjQ4MTAyZTQiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzI5Zjc1OGQzLTNhYTgtNGRmOS04NmYwLTkyNzQzZTBlZjY5MyIsImNvZ25pdG86Z3JvdXBzIjpbIk51cnNlIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5Iiwib3JpZ2luX2p0aSI6IjkxZmU4ZTgwLTJhYTEtNDVkMS1hNjkyLWExNjlhYTAzZDM1MiIsImV2ZW50X2lkIjoiNDZlMmNkNDEtY2ZhMi00MmRiLTk0ODEtMGU1MzNiZTNhZjFmIiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsImF1dGhfdGltZSI6MTY1NzE4ODI2MywiZXhwIjoxNjU3MTkxODY4LCJpYXQiOjE2NTcxODgyNjgsImp0aSI6ImM4ZjgzMDdjLTJlYTQtNDVlZS1hY2FkLTI1M2E5NGQ1OWNiOCIsInVzZXJuYW1lIjoiaWMtdGVzdC1udXJzZUBjYXBnZW1pbmkuY29tIn0.Te2ttlB2aCGzSo5Dx0EvJH_bBByZEQ3nznXA6SRphMDI6zKfcL9XbK_iRqKwcpJrj3uqiuuH-7EKbf0XoeE8lsfjLpjKqKJM2K-vvQkcw6GCloN3Jjcj8bIt29Z1oHPcesw-eBnjf_CuhggO9QQArYRh5X0DtwSDC5Fn67HR75t24gzuGiP1YisC5fRN5cA0DZ6qY0eTPNAuG5QVfL8Siob0f_PVXSN2AQ6CwDmVfcutW2xetlfLl3kvKWsKc_mLBzsj54_sh-KUB9ixORH2Pbaun7TYkO6HBr4aactIlxs4on5FSOUjDyTi1FzX7OIrr_IXElvXBJj_73n1DbNqLQ				|
# 		| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhNDk0MDA2OC1mMmNiLTQwNzktYTBlZC0yOTM1NTFjMzdiYjciLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzYxZjkyZTU3LTZjMDAtNGExOC1iYTg5LTQzMzc4NzFjM2NjZiIsImNvZ25pdG86Z3JvdXBzIjpbImgtYWRtaW4iLCJpYy1hZG1pbiJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9QaHdpNW13WWUiLCJjbGllbnRfaWQiOiI3anRwb25wcTRvdjh0MXUxcDlxdXU3ZTZzOSIsIm9yaWdpbl9qdGkiOiI3YWZkMzYxNi1mZGVkLTRjMDgtOTI0NS1mN2RmZTU5MmZjMGEiLCJldmVudF9pZCI6IjBjZTlmMDQ3LWE3ZTUtNGQ3OS1hYTE1LTc0MWMwMjhiMDQxMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTgyMTIyODQsImV4cCI6MTY1ODIxNTg4NCwiaWF0IjoxNjU4MjEyMjg0LCJqdGkiOiI4YTA4YzY4Zi05OTA5LTQyMDQtYWY2Mi05YzQ5Nzk4ZWFiMjUiLCJ1c2VybmFtZSI6ImgtdGVzdC1hZG1pbkBjYXBnZW1pbmkuY29tIn0.cdxel2pE0CE439BmNosIhC32PSX5jbxCMv7SbiIjFJqKvAX44hE6yfqsworiR7j0Byi9Y0eMmzIA-KTrsyt7yF1UnzdyXl3YNIaZvnZsgNiGlHJMXxznpKCf4z6LoV_TzhKkoQLrkoLblrDDC0wWmY5UWGRf30RdZr9NT6_YnHn3zZBo5e90h7deUhW3rt5YsaOE2Kkq4YVLbcR_FStw7Qtrl0NeuWL2YDWOaH0RUefT6V6djPFVhETwMr7pQTQLjo5CWjhi-zOR54o5NWDh8xDRqKbbVXLAsadR2dMF4Y6JOjS947EnmuMNotGt9LdPsO1smVIBDyq9rqkwBi7WBw|
# 		
# 		
# 	Scenario Outline: Get API to fetch linked faciltiy details for invalid users
# 	
# 		Given required base url, authorization "<key>" "<value>" are available
#		When get api is triggered to fetch linked facility details
#		Then verify status code 401 is returned for Get API to fetch linked facility details
#		And verify response body contains unauthorized error message with error code for Get API to fetch linked facility details
#		
#		Examples:
#		| key           | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                                                                                                     
#    	| Authorization | Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODZiNjdhYS1iZTllLTQ3YjUtYjYxZi1jNzM4ZTcwNWM1MDUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzFhZTI2MjViLTZjNWMtNGYxMC1hMTIyLWIzYmQyZGU2ZjUzZiIsImNvZ25pdG86Z3JvdXBzIjpbIm51bGwiXSwiaXNzIjoiaHR0cHM6Ly9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS91cy1lYXN0LTFfY1dNTmpDU1ZiIiwiY2xpZW50X2lkIjoiN245aGI0YnJyNHVuMmwwbTByNDBwOGY2OWoiLCJldmVudF9pZCI6ImJjMmRhZGY3LTc4YjktNDk2Ni05MzFmLWRlOTQ5YjIzZWI2NiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NDU1OTE3ODEsImV4cCI6MTY0NTU5NTQ1MiwiaWF0IjoxNjQ1NTkxODUyLCJqdGkiOiJjYzU4OWFlZC02YjI1LTQ5MGEtOTUzZC0zMTRjMDFjYjkxZGEiLCJ1c2VybmFtZSI6IlN1cmdlb25BQiJ9.lBU3zuVakf50AIyZIemFiGGkLjK5yC_t6WnE42oXWcg|
#    	
#    	
#    Scenario Outline: Get API to fetch linked facility details with invalid endpoint parameter for ic-admin, ic-user, surgeon, nurse, hospital-admin users
#	
#		Given required base url, authorization "<key>" "<value>" are available
#		When get api is triggered with invalid endpoint parameter to fetch linked facility details
#		Then verify status code 404 is returned for Get API to fetch linked facility details
#		And verify response body contains not found error message for Get API to fetch linked facility details
#		
#		Examples:
#		| key           | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       																										|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 																										|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1NGExZjhlZC02YjMyLTRkNTYtOGNmOC1iMmNhYmNlZTA0MGQiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzY2NDY5ZDU5LTc1NDMtNDk1NS05ODdlLTQ0ZmM4N2RmNjJhNSIsImNvZ25pdG86Z3JvdXBzIjpbImljLXVzZXIiXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfUGh3aTVtd1llIiwiY2xpZW50X2lkIjoiN2p0cG9ucHE0b3Y4dDF1MXA5cXV1N2U2czkiLCJvcmlnaW5fanRpIjoiZWUwNWMzMTYtYjFjMC00NzU2LWE4YjQtYmQyZmE5YjI4ODA3IiwiZXZlbnRfaWQiOiJiNTBmZjAxNy1hYWFmLTQwZmQtODEyNi0zNDFlYzY0MTI4OWIiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjU3MTc2NjYwLCJleHAiOjE2NTcxODAyNjQsImlhdCI6MTY1NzE3NjY2NCwianRpIjoiZDVjYTRiZWMtYTdiYi00YzNkLWEwYzUtMGVhZTlkMTg0NzViIiwidXNlcm5hbWUiOiJpYy10ZXN0LXRlY2hAY2FwZ2VtaW5pLmNvbSJ9.KS3NuFOIabgtcqmbkw9_2fKQG9FwpjnHxWf5073fLvWutlkCsmcpXpy_d8Iwxzfppqytqa6gp6DVLNY1LYHvrDFfeXAjnMoXhyGftPPs9bBdy4n52fzMJTZgVSKrqGML9VgVvxf9lBTrnECdowHE5VztZI-pSfOM7qfIqsYyNF00YFwe2pazFm766__lSNirikdIOe8wtEXp7IgUsPoevpsIOKvZE-R3b_PNit_Ryctc7k87EAAAYzsx-yb5M7YsY18zrfiSOLppJSXkP-QwG8qrqjO4y635GiKXj3lTirBVM5TvI-sB3rkBvLoZUwc3y0IuXWy5JaMJZhwZq9__QA				|
#   		| Authorization | Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2ODZiNjdhYS1iZTllLTQ3YjUtYjYxZi1jNzM4ZTcwNWM1MDUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzFhZTI2MjViLTZjNWMtNGYxMC1hMTIyLWIzYmQyZGU2ZjUzZiIsImNvZ25pdG86Z3JvdXBzIjpbInN1cmdlb24iXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfY1dNTmpDU1ZiIiwiY2xpZW50X2lkIjoiN245aGI0YnJyNHVuMmwwbTByNDBwOGY2OWoiLCJldmVudF9pZCI6ImJjMmRhZGY3LTc4YjktNDk2Ni05MzFmLWRlOTQ5YjIzZWI2NiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NDU1OTE3ODEsImV4cCI6MTY0NTU5NTQ1MiwiaWF0IjoxNjQ1NTkxODUyLCJqdGkiOiJjYzU4OWFlZC02YjI1LTQ5MGEtOTUzZC0zMTRjMDFjYjkxZGEiLCJ1c2VybmFtZSI6IlN1cmdlb25BQiJ9.RvhHXDsiv_3ldgC2gPqow0AuLIjfJrOL2-uxSZp7Yt5TDYFQ6-hp1BO99XHDsBCvzIK-dLUTJPhJoGokA68ySdvKanvukZQCwQo0yVUhUozbbMv2kvhMH29-85ekxymweRZOghEoGlAwYYFCoFSTsFWa_9Xd3gSYvfTzeAgDxVRn-rI-gt5LR-4FurMjCw6LdBNZJp4lQIY4PTQ8cJsfEqaDSGmgODr0-TniHJ5dpT2jZiTvv6HQKBoHAV5i8PAA6mjBg0HPrS2uuGXjTvqPIg9DLRf_eMNe1bFSQLvioOJuL2BZ0x6Wf1H8__0dfGaaSS1P5uUvTMDdc1DQNoVopQ 																											|
#    	| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI5OWZlZDM5Ny1lMDc5LTQzZTEtYjE0OS05MDZiZjQ4MTAyZTQiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzI5Zjc1OGQzLTNhYTgtNGRmOS04NmYwLTkyNzQzZTBlZjY5MyIsImNvZ25pdG86Z3JvdXBzIjpbIk51cnNlIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5Iiwib3JpZ2luX2p0aSI6IjkxZmU4ZTgwLTJhYTEtNDVkMS1hNjkyLWExNjlhYTAzZDM1MiIsImV2ZW50X2lkIjoiNDZlMmNkNDEtY2ZhMi00MmRiLTk0ODEtMGU1MzNiZTNhZjFmIiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsImF1dGhfdGltZSI6MTY1NzE4ODI2MywiZXhwIjoxNjU3MTkxODY4LCJpYXQiOjE2NTcxODgyNjgsImp0aSI6ImM4ZjgzMDdjLTJlYTQtNDVlZS1hY2FkLTI1M2E5NGQ1OWNiOCIsInVzZXJuYW1lIjoiaWMtdGVzdC1udXJzZUBjYXBnZW1pbmkuY29tIn0.Te2ttlB2aCGzSo5Dx0EvJH_bBByZEQ3nznXA6SRphMDI6zKfcL9XbK_iRqKwcpJrj3uqiuuH-7EKbf0XoeE8lsfjLpjKqKJM2K-vvQkcw6GCloN3Jjcj8bIt29Z1oHPcesw-eBnjf_CuhggO9QQArYRh5X0DtwSDC5Fn67HR75t24gzuGiP1YisC5fRN5cA0DZ6qY0eTPNAuG5QVfL8Siob0f_PVXSN2AQ6CwDmVfcutW2xetlfLl3kvKWsKc_mLBzsj54_sh-KUB9ixORH2Pbaun7TYkO6HBr4aactIlxs4on5FSOUjDyTi1FzX7OIrr_IXElvXBJj_73n1DbNqLQ				|
# 		| Authorization | Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhNDk0MDA2OC1mMmNiLTQwNzktYTBlZC0yOTM1NTFjMzdiYjciLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzYxZjkyZTU3LTZjMDAtNGExOC1iYTg5LTQzMzc4NzFjM2NjZiIsImNvZ25pdG86Z3JvdXBzIjpbImgtYWRtaW4iLCJpYy1hZG1pbiJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9QaHdpNW13WWUiLCJjbGllbnRfaWQiOiI3anRwb25wcTRvdjh0MXUxcDlxdXU3ZTZzOSIsIm9yaWdpbl9qdGkiOiI3YWZkMzYxNi1mZGVkLTRjMDgtOTI0NS1mN2RmZTU5MmZjMGEiLCJldmVudF9pZCI6IjBjZTlmMDQ3LWE3ZTUtNGQ3OS1hYTE1LTc0MWMwMjhiMDQxMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTgyMTIyODQsImV4cCI6MTY1ODIxNTg4NCwiaWF0IjoxNjU4MjEyMjg0LCJqdGkiOiI4YTA4YzY4Zi05OTA5LTQyMDQtYWY2Mi05YzQ5Nzk4ZWFiMjUiLCJ1c2VybmFtZSI6ImgtdGVzdC1hZG1pbkBjYXBnZW1pbmkuY29tIn0.cdxel2pE0CE439BmNosIhC32PSX5jbxCMv7SbiIjFJqKvAX44hE6yfqsworiR7j0Byi9Y0eMmzIA-KTrsyt7yF1UnzdyXl3YNIaZvnZsgNiGlHJMXxznpKCf4z6LoV_TzhKkoQLrkoLblrDDC0wWmY5UWGRf30RdZr9NT6_YnHn3zZBo5e90h7deUhW3rt5YsaOE2Kkq4YVLbcR_FStw7Qtrl0NeuWL2YDWOaH0RUefT6V6djPFVhETwMr7pQTQLjo5CWjhi-zOR54o5NWDh8xDRqKbbVXLAsadR2dMF4Y6JOjS947EnmuMNotGt9LdPsO1smVIBDyq9rqkwBi7WBw|
# 		