#Feature: Data Upload Utility (DUU) - View configuration
#
#	Scenario Outline: Post API to create user specific view configuration for ic-admin & hospital-admin with all required fields with unique values and with correct authorization
#	
#		Given required base url, authorization "<key>" "<value>" and content type "Content-Type" "application/json" are available to create specific view configuration
#		And post body is available with facility ID value <facilityId> and with isFacilityWide field set as false
#		When post api is triggered to create specific view configuration
#		Then verify status code 200 is returned for Post API to create specific view configuration
#		And verify response body contains success message with success code for successful creation of view configuration
#		
#	Examples:
#	#---Enter facilityID value which is not available in BE system in the facilityID column below before running this scenario	
#	| key         | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	  		 |facilityId|
#    |Authorization|Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 	  	 |94		|
#    |Authorization|Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkNmFkYzcxYi1jMDMyLTQzY2ItYjMwZi00Y2YxNTcxMjg5NzUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2U1ODdmZGFkLThmMTYtNDUxNi04Y2U1LWI0YWRkYmM4NWFjZCIsImNvZ25pdG86Z3JvdXBzIjpbImhvc3BpdGFsX2FkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2NXTU5qQ1NWYiIsImNsaWVudF9pZCI6IjduOWhiNGJycjR1bjJsMG0wcjQwcDhmNjlqIiwiZXZlbnRfaWQiOiI2ZDAzNzM0NS1mZjFiLTRiNmUtYjJmNi1iMmY0N2QwOWVjN2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjAwNTc2MzQ5LCJleHAiOjE2MDA1ODAxNjYsImlhdCI6MTYwMDU3NjU2NiwianRpIjoiYjBiOWJhMjItMTg2Yi00Nzc0LTlkNTMtNjkzNjlhMjEwYWU5IiwidXNlcm5hbWUiOiJkZXYxaGFkbWluIn0.C7CSCwY4iTzSOQ9s12QR3pYWLoj3kBsppkxNud4Lc-8KlNOS3G0PYzT-n_N67CuMWe5QxWsVw5UMAhFrB_P-2hfJyinKCXud0NZiwQjF7xdqRn7RHIGPZErH0PsfI81odP6yi5boeNcGXeMq9L03iMefkLGDn7N5FXhfY_ZuQP4b3P9WDBaaeUnB6XYnXTaOe-iPZtlZwhZlWMBlVxC5PigNUWCQOQnIiaw-D-YWrOWQB4Rqk-su5Vum-eLbR4glsuLUQZaUhXBhpEYriouJsyv9POuW-sRR30KtDUhO6iGFb5EUp-u6u7PdqnbIVsp-C8QpsF2dgjK-ikaP4YgHyg|95		|
#    
#    
#    Scenario Outline: Post API to create facility specific view configuration for ic-admin & hospital-admin with all required fields with unique values and with correct authorization
#	
#		Given required base url, authorization "<key>" "<value>" and content type "Content-Type" "application/json" are available to create specific view configuration
#		And post body is available with facility ID value <facilityId> and with isFacilityWide field set as true
#		When post api is triggered to create specific view configuration
#		Then verify status code 200 is returned for Post API to create specific view configuration
#		And verify response body contains success message with success code for successful creation of view configuration
#		
#	Examples:
#	#---Enter facilityID value which is not available in BE system in the facilityID column below before running this scenario	
#	| key         | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	  		 |facilityId|
#    |Authorization|Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 	  	 |96		|
#    |Authorization|Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkNmFkYzcxYi1jMDMyLTQzY2ItYjMwZi00Y2YxNTcxMjg5NzUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2U1ODdmZGFkLThmMTYtNDUxNi04Y2U1LWI0YWRkYmM4NWFjZCIsImNvZ25pdG86Z3JvdXBzIjpbImhvc3BpdGFsX2FkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2NXTU5qQ1NWYiIsImNsaWVudF9pZCI6IjduOWhiNGJycjR1bjJsMG0wcjQwcDhmNjlqIiwiZXZlbnRfaWQiOiI2ZDAzNzM0NS1mZjFiLTRiNmUtYjJmNi1iMmY0N2QwOWVjN2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjAwNTc2MzQ5LCJleHAiOjE2MDA1ODAxNjYsImlhdCI6MTYwMDU3NjU2NiwianRpIjoiYjBiOWJhMjItMTg2Yi00Nzc0LTlkNTMtNjkzNjlhMjEwYWU5IiwidXNlcm5hbWUiOiJkZXYxaGFkbWluIn0.C7CSCwY4iTzSOQ9s12QR3pYWLoj3kBsppkxNud4Lc-8KlNOS3G0PYzT-n_N67CuMWe5QxWsVw5UMAhFrB_P-2hfJyinKCXud0NZiwQjF7xdqRn7RHIGPZErH0PsfI81odP6yi5boeNcGXeMq9L03iMefkLGDn7N5FXhfY_ZuQP4b3P9WDBaaeUnB6XYnXTaOe-iPZtlZwhZlWMBlVxC5PigNUWCQOQnIiaw-D-YWrOWQB4Rqk-su5Vum-eLbR4glsuLUQZaUhXBhpEYriouJsyv9POuW-sRR30KtDUhO6iGFb5EUp-u6u7PdqnbIVsp-C8QpsF2dgjK-ikaP4YgHyg|97		|
#    
#    
#    Scenario Outline: Post API to create user/facility specific view configuration for ic-admin & hospital-admin without mandatory fields in request body and with correct authorization
#    
#    	Given required base url, authorization "<key>" "<value>" and content type "Content-Type" "application/json" are available to create specific view configuration
#    	And post body is available with no mandatory fields
#    	When post api is triggered to create specific view configuration
#    	Then verify status code 400 is returned for Post API to create specific view configuration
#    	And verify response body contains validation error message with error code while creation of view configuration
#    	
#    Examples:
#	| key         | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	  		 |
#    |Authorization|Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 	  	 |
#    |Authorization|Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkNmFkYzcxYi1jMDMyLTQzY2ItYjMwZi00Y2YxNTcxMjg5NzUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2U1ODdmZGFkLThmMTYtNDUxNi04Y2U1LWI0YWRkYmM4NWFjZCIsImNvZ25pdG86Z3JvdXBzIjpbImhvc3BpdGFsX2FkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2NXTU5qQ1NWYiIsImNsaWVudF9pZCI6IjduOWhiNGJycjR1bjJsMG0wcjQwcDhmNjlqIiwiZXZlbnRfaWQiOiI2ZDAzNzM0NS1mZjFiLTRiNmUtYjJmNi1iMmY0N2QwOWVjN2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjAwNTc2MzQ5LCJleHAiOjE2MDA1ODAxNjYsImlhdCI6MTYwMDU3NjU2NiwianRpIjoiYjBiOWJhMjItMTg2Yi00Nzc0LTlkNTMtNjkzNjlhMjEwYWU5IiwidXNlcm5hbWUiOiJkZXYxaGFkbWluIn0.C7CSCwY4iTzSOQ9s12QR3pYWLoj3kBsppkxNud4Lc-8KlNOS3G0PYzT-n_N67CuMWe5QxWsVw5UMAhFrB_P-2hfJyinKCXud0NZiwQjF7xdqRn7RHIGPZErH0PsfI81odP6yi5boeNcGXeMq9L03iMefkLGDn7N5FXhfY_ZuQP4b3P9WDBaaeUnB6XYnXTaOe-iPZtlZwhZlWMBlVxC5PigNUWCQOQnIiaw-D-YWrOWQB4Rqk-su5Vum-eLbR4glsuLUQZaUhXBhpEYriouJsyv9POuW-sRR30KtDUhO6iGFb5EUp-u6u7PdqnbIVsp-C8QpsF2dgjK-ikaP4YgHyg|
#
#
#	Scenario Outline: Post API to create user/facility specific view configuration for ic-admin & hospital-admin with all required fields with existing values and with correct authorization
#	
#		Given required base url, authorization "<key>" "<value>" and content type "Content-Type" "application/json" are available to create specific view configuration
#		And post body is available with facility ID value <facilityId> and with isFacilityWide field set as true
#		When post api is triggered to create specific view configuration
#		Then verify status code 409 is returned for Post API to create specific view configuration
#		And verify response body contains error message with error code for configuration creation conflict
#	
#	Examples:
#	| key         | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	  		 |facilityId|
#    |Authorization|Bearer eyJraWQiOiJIcDhlNUxOY21nTVFpTXIrZEdRblpwbnVcL0owc3U2MnVaUW9Dbm5IRjZ5cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjOWY1NjI2YS1jYTdhLTRlMzItYjE3MC05OTc0MWMwZWQzM2MiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2NkZjI0M2ZkLThjZWMtNDliMi04YTE1LThhNTYxZmRmMjk1NyIsImNvZ25pdG86Z3JvdXBzIjpbImljLWFkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1Bod2k1bXdZZSIsImNsaWVudF9pZCI6IjdqdHBvbnBxNG92OHQxdTFwOXF1dTdlNnM5IiwiZXZlbnRfaWQiOiI1OWFmZjA4MS1lM2E5LTRlZjEtYjc0Mi0wMWMxMjU3ZDBiNGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQyNzYxMTUzLCJleHAiOjE2NDI3NjQ5NDEsImlhdCI6MTY0Mjc2MTM0MSwianRpIjoiNmVjZmE1YTUtOGY1MS00M2NhLWFkZDYtN2Y4ODIyN2QxMTE5IiwidXNlcm5hbWUiOiJzaXZha3VtYXIyMSJ9.kbmCvBGeS2EWrGvoe-5e2EiaJ1M_4koEeys_nZrboECYl3OOCVms21JXbRjxFJjkMDz7XcUMe-wO7_suHfuLnitj5lSKbPIWJ1ezvz125z2hBXED60MrSPLHNUGAK-Ux4t41hL19MZfKlLdl6M8BzxXzN-hwlsNP6qDK1I1IgoFavo1-g4WNXDRsiXctPVYXCVT8c1HlEyhTKTamK33jKjQQDLBD0o6DeccJ1mOqToEl2WirYBbrGCTEnRUwApTp2Y9bEmagpvVxFQjgyVCd3h7I5DUaCAvQc45PlsTwWZw0Pwf7T5NBjrdYGwH82Qvhz1AgPnliUxZXMxzJxX5bYQ 	  	 |80		|
#    |Authorization|Bearer eyJraWQiOiJMXC9HWGVmR09mRXhvSzdVQWE3WHhJejY2WWRqYlR6am8wa0x5bHc0bDdSWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkNmFkYzcxYi1jMDMyLTQzY2ItYjMwZi00Y2YxNTcxMjg5NzUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xX2U1ODdmZGFkLThmMTYtNDUxNi04Y2U1LWI0YWRkYmM4NWFjZCIsImNvZ25pdG86Z3JvdXBzIjpbImhvc3BpdGFsX2FkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2NXTU5qQ1NWYiIsImNsaWVudF9pZCI6IjduOWhiNGJycjR1bjJsMG0wcjQwcDhmNjlqIiwiZXZlbnRfaWQiOiI2ZDAzNzM0NS1mZjFiLTRiNmUtYjJmNi1iMmY0N2QwOWVjN2UiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjAwNTc2MzQ5LCJleHAiOjE2MDA1ODAxNjYsImlhdCI6MTYwMDU3NjU2NiwianRpIjoiYjBiOWJhMjItMTg2Yi00Nzc0LTlkNTMtNjkzNjlhMjEwYWU5IiwidXNlcm5hbWUiOiJkZXYxaGFkbWluIn0.C7CSCwY4iTzSOQ9s12QR3pYWLoj3kBsppkxNud4Lc-8KlNOS3G0PYzT-n_N67CuMWe5QxWsVw5UMAhFrB_P-2hfJyinKCXud0NZiwQjF7xdqRn7RHIGPZErH0PsfI81odP6yi5boeNcGXeMq9L03iMefkLGDn7N5FXhfY_ZuQP4b3P9WDBaaeUnB6XYnXTaOe-iPZtlZwhZlWMBlVxC5PigNUWCQOQnIiaw-D-YWrOWQB4Rqk-su5Vum-eLbR4glsuLUQZaUhXBhpEYriouJsyv9POuW-sRR30KtDUhO6iGFb5EUp-u6u7PdqnbIVsp-C8QpsF2dgjK-ikaP4YgHyg|81		|	
#
#	
#	Scenario Outline: Post API to create user/facility specific view configuration with all required fields but with not authorized user
#	
#		Given required base url, authorization "<key>" "<value>" and content type "Content-Type" "application/json" are available to create specific view configuration
#		And post body is available with facility ID value <facilityId> and with isFacilityWide field set as true
#		When post api is triggered to create specific view configuration
#		Then verify status code 401 is returned for Post API to create specific view configuration
#		And verify response body contains error message with error code for incorrect authorization during view configuration creation
#		
#	Examples:
#	| key         | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |facilityId|
#    |Authorization|Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODZiNjdhYS1iZTllLTQ3YjUtYjYxZi1jNzM4ZTcwNWM1MDUiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0xXzFhZTI2MjViLTZjNWMtNGYxMC1hMTIyLWIzYmQyZGU2ZjUzZiIsImNvZ25pdG86Z3JvdXBzIjpbIm51bGwiXSwiaXNzIjoiaHR0cHM6Ly9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS91cy1lYXN0LTFfY1dNTmpDU1ZiIiwiY2xpZW50X2lkIjoiN245aGI0YnJyNHVuMmwwbTByNDBwOGY2OWoiLCJldmVudF9pZCI6ImJjMmRhZGY3LTc4YjktNDk2Ni05MzFmLWRlOTQ5YjIzZWI2NiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NDU1OTE3ODEsImV4cCI6MTY0NTU5NTQ1MiwiaWF0IjoxNjQ1NTkxODUyLCJqdGkiOiJjYzU4OWFlZC02YjI1LTQ5MGEtOTUzZC0zMTRjMDFjYjkxZGEiLCJ1c2VybmFtZSI6IlN1cmdlb25BQiJ9.lBU3zuVakf50AIyZIemFiGGkLjK5yC_t6WnE42oXWcg|84		  |